P16
Trayvor/mate-hw-bookstore pull request #16
Opened 2024-09-06 06:20 UTC by Trayvor

2024-09-06 12:50 UTC, Elena-Bruyako requested changes
see comments

2024-09-06 12:50 UTC, Elena-Bruyako commented on src/main/java/org/example/bookstore/model/Order.java
> +    @OneToMany(mappedBy = "order", fetch = FetchType.LAZY, cascade = CascadeType.ALL,
```suggestion
    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL,
```

2024-09-06 12:50 UTC, Elena-Bruyako commented on src/main/java/org/example/bookstore/model/Order.java
> +    @Column(nullable = false, unique = true)
```suggestion
    @Column(nullable = false)
```

2024-09-06 12:50 UTC, Elena-Bruyako commented on src/main/java/org/example/bookstore/model/Order.java
> +    @ManyToOne(fetch = FetchType.LAZY)
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2024-09-06 12:50 UTC, Elena-Bruyako commented on src/main/java/org/example/bookstore/service/impl/OrderServiceImpl.java
> +        shoppingCartService.deleteAllFromShoppingCart(userId);
Instead of this method, you can just create in ShoppingCart
```
public void clearCart() {
        cartItems.clear();
    }
```

2024-09-06 12:50 UTC, Elena-Bruyako commented on src/main/java/org/example/bookstore/model/Order.java
> +    private Status status;
you can set status Pending here straightaway

2024-09-06 12:50 UTC, Elena-Bruyako commented on src/main/java/org/example/bookstore/model/Order.java
> +    private LocalDateTime orderDate;
same as status 
```suggestion
    private LocalDateTime orderDate = LocalDateTime.now();
```

2024-09-06 12:50 UTC, Elena-Bruyako commented on src/main/java/org/example/bookstore/service/impl/OrderServiceImpl.java
> +        order.setStatus(Status.PENDING);
```suggestion
```

see comment in Order model

2024-09-06 12:50 UTC, Elena-Bruyako commented on src/main/java/org/example/bookstore/service/impl/OrderServiceImpl.java
> +        Order order = createBlankOrder(createOrderRequestDto, userId);
Other option of implementation

```suggestion
        Order order = orderMapper.cartToOrder(cart, orderDto.shippingAddress());
        shoppingCart.clearCart();
        return....
```

Where in OrderMapper

```
@Mapping(target = "id", ignore = true)
@Mapping(target = "total", source = "cart.cartItems", qualifiedByName = "total")
@Mapping(target = "orderItems", source = "cart.cartItems")
Order cartToOrder(ShoppingCart cart, String shippingAddress);
```

```
@AfterMapping
    default void updateOrder(@MappingTarget Order order) {
        order.getOrderItems().forEach(oi -> oi.setOrder(order));
    }

    @Named("total")
    default BigDecimal getTotal(Set<CartItem> cartItems) {
        return cartItems.stream()
                .map(i -> i.getBook().getPrice().multiply(BigDecimal.valueOf(i.getQuantity())))
                .reduce(BigDecimal.ZERO, BigDecimal::add);
    }

```

and in OrderItemMapper

```
@Mapping(target = "id", ignore = true)
@Mapping(target = "price", source = "book.price")
OrderItem cartItemToOrderItem(CartItem cartItem);
```

2024-09-07 16:26 UTC, okuzan approved these changes

2024-09-07 16:26 UTC, okuzan commented on src/main/java/org/example/bookstore/service/impl/OrderServiceImpl.java
> +        order.setTotal(new BigDecimal(0));
```suggestion
        order.setTotal(BigDecimal.ZERO);
```

2024-09-08 13:47 UTC, merged