Docker
Trayvor/mate-hw-bookstore pull request #17
Opened 2024-09-09 16:31 UTC by Trayvor

2024-09-10 07:31 UTC, Elena-Bruyako requested changes
see comments

2024-09-10 07:31 UTC, Elena-Bruyako commented on .gitignore
> +
.env.sample should contains 

```
MYSQLDB_ROOT_PASSWORD=
MYSQLDB_DATABASE=
MYSQLDB_USER=
MYSQLDB_PASSWORD=
MYSQLDB_LOCAL_PORT=
MYSQLDB_DOCKER_PORT=

SPRING_LOCAL_PORT=
SPRING_DOCKER_PORT=
DEBUG_PORT=
```

2024-09-10 07:31 UTC, Elena-Bruyako commented on src/main/java/org/example/bookstore/service/impl/UserServiceImpl.java
> +        user.setRoles(Set.of(userRole));
```suggestion
        user.setRoles(Set.of(userRole));
        userRepository.save(user);
```

2024-09-11 08:49 UTC, okuzan approved these changes

2024-09-11 08:55 UTC, merged