Replaced old repository with new one. Addded liquibase support. Imple…
Trayvor/mate-hw-bookstore pull request #5
Opened 2024-07-24 19:32 UTC by Trayvor

…mented safe delete concept for Book entity. Added new endpoints to BookController and BookService

2024-07-25 13:51 UTC, MentorMateAcademy requested changes

2024-07-25 13:51 UTC, MentorMateAcademy commented on .jpb/jpb-settings.xml
> +</project>
Is it mandatory?

2024-07-25 18:43 UTC, Elena-Bruyako requested changes
Good job! let's improve it

2024-07-25 18:43 UTC, Elena-Bruyako commented on src/main/java/org/example/bookstore/model/Book.java
> +    @Column(name = "cover_image")
```suggestion
```

2024-07-25 18:43 UTC, Elena-Bruyako commented on src/main/java/org/example/bookstore/service/impl/BookServiceImpl.java
> +        model.setId(id);
```suggestion
        Book book = bookRepository.findById(id)
                .orElseThrow(() ....
        bookMapper.updateBookFromDto(bookDto, book);
```

2024-07-25 19:32 UTC, Trayvor commented on src/main/java/org/example/bookstore/service/impl/BookServiceImpl.java
> +        model.setId(id);
what is incorrect here?

2024-07-26 07:21 UTC, Elena-Bruyako approved these changes

2024-07-26 10:52 UTC, merged